gps/urls.py
from django.urls import path
from gps.views import update_location,upload,map_view,map_page
urlpatterns = [
    path('location/',update_location,name='update_location'),
    path('api/upload/',upload, name='upload'),
    path('map-data/', map_view, name='map_data'),
    path('map/',map_page, name='map_page'),
]

log/urls.py
from log.views import login,logon,logout,index
from django.urls import path

urlpatterns = [
    path('',index,name='login'),
    path('index/',index,name='index'),
    path("logon/",logon,name='logon'),
    path("logout/",logout,name='logout'),
]

orders/urls.py
# urls.py
from django.urls import path

from .views import assign_task_view

app_name = 'tasks'

urlpatterns = [
    path('assign_task/', assign_task_view, name='assign_task'),
]

system/urls.py
from django.contrib import admin
from django.urls import include, path
import log
from log import urls

from django.urls import re_path
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
   path("admin/", admin.site.urls),
   path('',include('log.urls')),
   path('',include('gps.urls')),
   path('',include('orders.urls')),
   re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

gps/models.py
from django.db import models
from django.db.models import Model
# Create your models here.
from django.utils import timezone

class Location(models.Model):
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField()
    class Meta:
        verbose_name = "定位"
        verbose_name_plural = "定位"

class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='images')

log/models.py
from django.db import models
from django.db.models import Model
# Create your models here.
class Account(models.Model):
    password=models.CharField(max_length=200)
    name=models.CharField(max_length=20)

orders/models.py
from django.db import models
from gps.models import Location
# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone_number = models.CharField(max_length=20)
    department = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    STATUS_CHOICES = [
        ('NEW', '正在进行'),
        ('InProgress', '正在进行'),
        ('Completed', '已完成'),
    ]
    status=models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='NEW',
    )
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = '派单任务'
        verbose_name_plural = '任务列表'  # 设置复数的显示

gps/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Location, Image

from django.views.decorators.csrf import csrf_exempt


# Create your views here.



@api_view(['POST'])
def upload(request):
    longitude = request.data.get('longitude')
    latitude = request.data.get('latitude')
    image_file = request.FILES.get('image')

    # 保存定位信息
    location = Location.objects.create(longitude=longitude, latitude=latitude)

    # 保存图片
    image = Image.objects.create(location=location, image=image_file)

    return Response({'status': 'success'})



#在百度地图中显示
def update_location(request):
    if request.method == 'POST':
        address_point = Location.objects.all()
        address_longitude = []
        address_latitude = []
        address_data = []
        for i in range(len(address_point)):
            address_longitude.append(address_point[i].longitude)
            address_latitude.append(address_point[i].latitude)
            address_data.append('施工地点')
    return render(request, 'display.html',
                  {'address_longitude': json.dumps(address_longitude),
                   'address_latitude': json.dumps(address_latitude), 'address_data': json.dumps(address_data)})

@csrf_exempt
def map_view(request):
    locations = Location.objects.all()
    data = []
    for loc in locations:
        images = Image.objects.filter(location_id=loc.id)
        img_urls = [img.image.url for img in images]
        data.append({
            'lng': loc.longitude,
            'lat': loc.latitude,
            'images': img_urls
        })
    return JsonResponse({'data': data})

#页面显示
def map_page(request):
    return render(request, 'map.html')

log/views.py
from django.shortcuts import render, HttpResponse
from .models import Account


#主页面

#登录页面
def login(request):
    # 处理用户提交的表单数据
    return render(request, 'login.html')



# 登录按钮提交后，验证数据库中是否存在用户,存在就跳转主网页
def index(requst):
    u = requst.POST.get('username','')
    p = requst.POST.get('password','')
    if u and p:
        user = Account.objects.filter(name=u,password=p).count()
        if user>=1:
            return render(requst, 'index.html')
        else:
            error_msg='用户名或密码错误，请联系管理员'
            return render(requst, 'login.html',{'error_msg':error_msg})
    else:
        return render(requst, 'login.html')


#注册页面
def logon(request):
    # 渲染注册页面
    if request.method == 'POST':
        return render(request, 'login.html')
    
    return render(request, 'regist.html')

#退出页面
def logout(request):
    # 渲染退出页面
    return HttpResponse('退出')

orders/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task, Employee


# Create your views here.
def assign_task_view(request):
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        employee_id = request.POST.get('employee_id')
        task = get_object_or_404(Task, pk=task_id)
        employee = get_object_or_404(Employee, pk=employee_id)
        task.assigned_to = employee
        task.save()
        return redirect('admin:tasks_task_changelist')

    tasks = Task.objects.filter(assigned_to=None)
    employees = Employee.objects.all()
    return render(request, 'assign_task.html', {'tasks': tasks, 'employees': employees})

gps/templates/display.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
    <style type="text/css">
        body, html {
            width: 100%;
            height: 100%;
            margin: 0;
            font-family: "微软雅黑";
        }

        #allmap {
            height: 700px;
            width: 100%;
        }

        #r-result {
            width: 100%;
            font-size: 14px;
        }
    </style>
    <script type="text/javascript"
            src="http://api.map.baidu.com/api?v=2.0&ak=OxFoB6mKG2IsvrI724oRAIUKCi9pER8Z"></script>
    <title>经纬度定位</title>
</head>
<body>
<div id="allmap"></div>
<div id="r-result">
    <input type="button" value="获取我的位置" onclick="get_location()"/>
</div>
</body>
</html>

<script type="text/javascript">
    // 百度地图API功能
    var map = new BMap.Map("allmap");
    map.centerAndZoom(new BMap.Point(113.15,23.06), 12);
    map.enableScrollWheelZoom(true);
    var navigationControl = new BMap.NavigationControl({
        // 靠左上角位置
        anchor: BMAP_ANCHOR_TOP_LEFT,
        // LARGE类型
        type: BMAP_NAVIGATION_CONTROL_LARGE,
        // 启用显示定位
        enableGeolocation: true
    });
    map.addControl(navigationControl);

    function get_location() {

        var address_latitude ={{ address_latitude |safe}};
        var address_longitude ={{ address_longitude|safe }};
        var address_data ={{ address_data |safe}};

        var point = []; //存放标注点经纬信息的数组
        var marker = []; //存放标注点对象的数组
        for (var i = 0; i < address_longitude.length; i++) {
            point[i] = new BMap.Point(address_longitude[i], address_latitude[i]); //循环生成新的地图点
            marker[i] = new BMap.Marker(point[i]); //按照地图点坐标生成标记
            map.addOverlay(marker[i]);
        }

        for (i = 0; i < marker.length; i++) {
            (function () {
                var index = i;
                marker[index].addEventListener('click', function () {
                    this.openInfoWindow(new BMap.InfoWindow(address_data[index]));
                });
            })();
        }
    }

</script>

gps/templates/map.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>车载智能巡检管理系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <style>
    body,
    html,
    #container {
        overflow: hidden;
        width: 100%;
        height: 100%;
        margin: 0;
        font-family: "微软雅黑";
    }
    </style>
    <script src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=OxFoB6mKG2IsvrI724oRAIUKCi9pER8Z"></script>
    <script src="//cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <div id="container"></div>
</body>
</html>

<script>
var map = new BMapGL.Map('container');
var point = new BMapGL.Point(113,23.047981);
map.addOverlay(point);
map.centerAndZoom(point, 15);
map.enableScrollWheelZoom(true);
// 异步请求JSON数据并解析
$.getJSON('http://192.168.1.104:8000/map-data/', function(data) {
    if (data && data.data) {
        var locations = data.data;
        locations.forEach(function(loc) {
            var marker = new BMapGL.Marker(new BMapGL.Point(loc.lng, loc.lat));
            map.addOverlay(marker);
            // 添加弹出窗口
            var contentString = '<div>';
            img_url2='/media/images/result.jpg'
            img_url1='https://ts1.cn.mm.bing.net/th/id/R-C.63626c112fd6f219719949f27a73fff7?rik=wjkNnlzHFEeb6w&riu=http%3a%2f%2fwww.evask360.com%2fdata%2fattach%2f1809%2fY0YBTKna.png&ehk=NkVn2XFPqbAnq77%2fkQ1fo5a4Ag51V%2fJZWyo5t8SS4iM%3d&risl=&pid=ImgRaw&r=0'
            loc.images.forEach(function(img_url) {
                contentString += '<img src="' + img_url + ' " style="max-width: 100%;">';
            });
            contentString += '</div>';
            var infoWindow = new BMapGL.InfoWindow(contentString);
            marker.addEventListener('click', function() {
                this.openInfoWindow(infoWindow);
            });
        });
    }
});
</script>

log/templates/1.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>控制面板</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Theme style -->
    <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/AdminLTE.min.css">
</head>

<body>
<div class="wrapper">
 <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ user_count }}</h3>

                <p>用户总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ task_count }}</h3>
                <p>任务总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
             <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ user_count }}</h3>

                <p>用户总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ task_count }}</h3>

                <p>任务总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->

        </div>
      </div>
    </section>
  </div>
</body> 

log/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>控制面板</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Theme style -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/AdminLTE.min.css">
</head>

<body>
<div class="wrapper">
 <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ user_count }}</h3>

                <p>用户总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ task_count }}</h3>
                <p>任务总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
             <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ user_count }}</h3>

                <p>用户总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ task_count }}</h3>

                <p>任务总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->

        </div>
      </div>
    </section>
  </div>
</body> 

log/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>登陆</title>
  <style>
    body {
      background-image: url("{% static 'img/image.png' %}");
      background-size: 100% 100%;;
      background-position: center;
    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .login {
      max-width: 400px;
      width: 100%;
      padding: 20px;
      background-color: #fff;
      border: 1px solid #ddd;
      border-radius: 5px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    .login-header {
      text-align: center;
      margin-bottom: 20px;
    }

    .login-body {
      margin-bottom: 20px;
    }

    .ui.form button {
      margin-top: 10px;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="login">
      <div class="login-header">
        <h3 class="ui header">车载智能巡检管理系统</h3>
      </div>
      <div class="login-body">
        <form action="/index/" method="post" class="ui form">
          {% csrf_token %}
          <div class="ui error message">{{ msg }}</div>
          <div class="field">
            <label for="username">用户名：</label>
            <input type="text" name="username" placeholder="请输入用户名">
          </div>
          <div class="field">
            <label for="password">密码：</label>
            <input type="password" name="password" placeholder="请输入密码">
          </div>
          <button type="submit" class="ui primary button">登录</button>
        </form>
        <p>{{ rlt }}</p>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/semantic-ui/2.4.2/semantic.min.js"></script>
  <script>
    $('.message .close').on('click', function() {
      $(this).closest('.message').transition('fade');
    });
  </script>
</body>

</html>

log/templates/regist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <title>注册</title>
</head>

<body>
    <div style="width: 70%; margin: 0 auto; padding-top: 20em;padding-bottom: 20em;">   
          <div class="ui stackable centered column grid">
            <div class="centered row">
              <div class="six wide column">
                <div style="padding-bottom: 5em; background-color: rgba(245, 245, 245,0.5);" class="ui segment">
                  <form action="/regist/" method="POST" class="ui form">
                    {% csrf_token %}
                    <h3 style="color: red;">{{ msg }}</h3>
                    <div class="field">
                      <label for="username">用户名：</label>
                      <input type="text" name="username" id="">
                    </div>
                    <div class="field">
                      <label for="password">密码：</label>
                      <input type="password" name="password" id="">
                    </div>
                    <div class="field">
                      <label for="password2">重复密码：</label>
                      <input type="password" name="password2" id="">
                    </div>
                    <div class="field">
                      <label for="email">Email：</label>
                      <input type="text" name="email" id="">
                    </div>
                    <input style="float: right;" class="ui inverted green button" type="submit" value="注册">
                  </form>
                </div>  
              </div>
            </div>
          </div>
       
    </div>
</body>

</html>

orders/templates/assign_task.html
<!-- assign_task.html -->
<form method="post" action="{% url 'tasks:assign_task' %}">
    {% csrf_token %}
    <label for="task">Select a task:</label>
    <select name="task_id" id="task">
        {% for task in tasks %}
            <option value="{{ task.id }}">{{ task.name }}</option>
        {% endfor %}
    </select>
    <br>
    <label for="employee">Select an employee:</label>
    <select name="employee_id" id="employee">
        {% for employee in employees %}
            <option value="{{ employee.id }}">{{ employee.name }}</option>
        {% endfor %}
    </select>
    <br>
    <button type="submit">Assign Task</button>
</form>